### ISSUE TITLE
GitHub Pages failed to build your site.

### ISSUE THREAD

**Issue by yuceltoluyag** [t-richards/jekyll-google-tag-manager#12]
The tag gtm on line 5 in /_layouts/default.html is not a recognized Liquid tag.

https://github.com/yuceltoluyag/yuceltoluyag.github.io/runs/411146996

https://github.com/yuceltoluyag/yuceltoluyag.github.io/blob/3985e91b1a0ea7d6a1219b1ef3736e8bafb5f7b7/_layouts/default.html#L5

**Comment by t-richards** [comment]
Hi @yuceltoluyag,

Unfortunately, GitHub Pages does not support running custom plugins (such as `jekyll-google-tag-manager`) for "security reasons". You can find a complete list of plugins which are allowed in GitHub Pages here: https://pages.github.com/versions/

One way to fix your site might be to copy the liquid templates from this gem and place them directly in your `_includes` folder. You would then directly include them `{% include gtm/head.html %}` instead of using the gtm tag.

Hope this helps!

**Comment by yuceltoluyag** [comment]
@t-richards Thank u for answer, Cheers (^̮^)
